language: cpp
sudo: false

compiler:
  - gcc
  - clang

addons:
    apt:
      packages:
       - qtbase5-dev
       - qt5-default
       - qt5-qmake


before_script:
  - qmake --version
  - qmake -d

script:
  - make
  - cd tests && qmake && make && ./TestVCardParser
